version: "3"
services:
  heroes-gui:
    image: stigbd/heroes-gui
    ports:
      - "80:80"
  heroes-service:
    image: stigbd/heroes-service
    ports:
      - "3002:3002"
    environment:
      - DBHOST=database
    depends_on:
      - database
  authentication-service:
    image: stigbd/authentication-service
    ports:
      - "3003:3003"
    environment:
      - DBHOST=database
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"
